server:
    port: 8000
    servlet:
        context-path: /api
    tomcat:
        basedir: "tomcat"
        accesslog:
            enabled: true
            directory: access
        additional-tld-skip-patterns: "j2objc-annotations-1.1.jar, checker-compat-qual-2.5.2.jar, guava-26.0-android.jar, animal-sniffer-annotations-1.17.jar, jsr305-3.0.2.jar, error_prone_annotations-2.3.2.jar, opencensus-api-0.21.0.jar, opencensus-contrib-grpc-metrics-0.21.0.jar, perfmark-api-0.17.0.jar, annotations-4.1.1.4.jar, gson-2.7.jar, grpc-*.jar"

spring:
    application:
        name: COVID-19
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/covid19_db?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
        hikari.maximumPoolSize: 25
    idhs:
        url: http://43.224.124.234:7080/api
        username: dev
        password: Dev12345#
    pid:
        file: application.pid
    portal:
        userCredentials:
        - [dev, dev]
        - [dev2@aaa.com, dev]
    googleapi:
        mapKey: abc
    session:
        timeout: 3600
        jdbc:
            initialize-schema: always
            schema: classpath:session/schema-mysql.sql
            initializer:
                enabled: true

firebase:
    config-path: credentials/covid-19-lk-dev-firebase-adminsdk.json
    topic: 'mobile_message' #use mobile_message_test for test env

webapp:
    war:
        filename: portal.war
        context: ''
